### ISSUE TITLE
Installing the bundle in a path with non-ascii characters breaks

### ISSUE THREAD

**Issue by gdementen** [liam2/liam2#229]
See users mailing list: https://groups.google.com/d/msg/liam2-users/qu-h-vJHPKQ/51CsXcKmBAAJ

I could reproduce the issue with 0.11.

```python traceback
Traceback (most recent call last):
  File "Console.py", line 27, in <module>
  File "main.py", line 21, in <module>
  File "console.py", line 8, in <module>
  File "entities.py", line 17, in <module>
  File "exprtools.py", line 13, in <module>
  File "charts.py", line 15, in <module>
  File "matplotlib\__init__.py", line 1100, in <module>
  File "matplotlib\__init__.py", line 947, in rc_params
  File "matplotlib\__init__.py", line 789, in matplotlib_fname
  File "matplotlib\__init__.py", line 325, in wrapper
  File "matplotlib\__init__.py", line 693, in _get_data_path_cached
  File "matplotlib\__init__.py", line 661, in _get_data_path
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 9: ordinal not in range(128)
```

**Comment by gdementen** [comment]
updating matplotlib to 1.5+ should solve the issue

https://www.bountysource.com/issues/43523823-matplotlib-failing-to-import-when-running-from-unicode-path

**Comment by gdementen** [comment]
the note in install.rst should be updated when this is fixed
