### ISSUE TITLE
Compression error

### ISSUE THREAD

**Issue by benjello** [liam2/liam2#301]
I tried to compress my simulation by adding the following line in my import file 
```yaml
compression: bzip2
```

I got the following error
```
ERROR: atom parameter should be an instance of tables.Atom and you passed a <class 'liam2.utils.LabeledArray'>.
```

The `error.log` file reads:
```
Traceback (most recent call last):
  File "/home/benjello/.local/bin/liam2", line 11, in <module>
    load_entry_point('liam2', 'console_scripts', 'liam2')()
  File "/home/benjello/openfisca/liam2/liam2/main.py", line 365, in main
    return func(*args)
  File "/home/benjello/openfisca/liam2/liam2/importer.py", line 786, in csv2h5
    compression=compression)
  File "/home/benjello/openfisca/liam2/liam2/importer.py", line 357, in array_to_disk_array
    filters=filters)
  File "/usr/lib/python2.7/dist-packages/tables/file.py", line 1275, in create_carray
    track_times=track_times)
  File "/usr/lib/python2.7/dist-packages/tables/carray.py", line 194, in __init__
    type(atom))
ValueError: atom parameter should be an instance of tables.Atom and you passed a <class 'liam2.utils.LabeledArray'>
```

I use liam2 0.12.0 version and `liam2 --version` output is
```
C extensions are available

python 2.7.16 (64bit)
numpy 1.16.2
numexpr 2.6.8
pytables 3.4.4
bcolz N/A
pyyaml 3.13
vitables N/A
matplotlib 2.2.3
``` 

@gdementen any hint ?

**Comment by benjello** [comment]
After a remark by @benbel I isntalled bcolz but I still have the error.
```
C extensions are available

python 2.7.16 (64bit)
numpy 1.16.2
numexpr 2.6.8
pytables 3.4.4
bcolz 1.2.1
pyyaml 3.13
vitables N/A
matplotlib 2.2.3
```

**Comment by gdementen** [comment]
In 0.12, liam2.utils.LabeledArray is a subclass of np.ndarray, so it is probably a bug in pytables that it supports ndarray but not its subclasses for compressed arrays (I suppose it does support ndarray subclasses for non compressed arrays otherwise the whole import code would always fail).

In any case and AFAICT, this is already fixed in master/for 0.13 because of the line:
array_data = np.asarray(array)
https://github.com/liam2/liam2/blob/master/liam2/importer.py#L355

I am leaving the issue open to remember to add a test case for it.
