### ISSUE TITLE
Import empty entities not working (at least in version 0.12)

### ISSUE THREAD

**Issue by benjello** [liam2/liam2#319]
Trying to import this simple import file (from the doc)

```yaml
output: simplest.h5

entities:
    household: {}
    person: {}
```
yields

```shell
liam2 import liam2/agirc_arrco/import_test.yml 
Warning: the 'view' command is not available because 'PyQt4.QtGui' could not be imported (No module named PyQt4).
/home/mbenjelloul/openfisca/liam2/liam2/importer.py:697: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  content = yaml.load(f)
Importing in /home/mbenjelloul/openfisca/agirc-arrco-group/modeles/liam2/agirc_arrco/simplest.h5

entities
--------

 person

ERROR: [Errno 2] No such file or directory: '/home/mbenjelloul/openfisca/agirc-arrco-group/modeles/liam2/agirc_arrco/person.csv'
```

`error.log` looks like:

```shell
Traceback (most recent call last):
  File "/home/mbenjelloul/.virtualenvs/aa/bin/liam2", line 11, in <module>
    load_entry_point('liam2', 'console_scripts', 'liam2')()
  File "/home/mbenjelloul/openfisca/liam2/liam2/main.py", line 365, in main
    return func(*args)
  File "/home/mbenjelloul/openfisca/liam2/liam2/importer.py", line 807, in csv2h5
    entity_def, [('period', int), ('id', int)])
  File "/home/mbenjelloul/openfisca/liam2/liam2/importer.py", line 608, in load_def
    delimiter=',', transpose=transpose)
  File "/home/mbenjelloul/openfisca/liam2/liam2/importer.py", line 166, in __init__
    f = open(fpath, "rb")
IOError: [Errno 2] No such file or directory: '/home/mbenjelloul/openfisca/agirc-arrco-group/modeles/liam2/agirc_arrco/person.csv'
```

**Comment by gdementen** [comment]
Please read the error message! You have a missing data file. It has nothing to do with the import file.

**Comment by benbel** [comment]
IMHO it would be more explicit to have:
```
entities:
    household: default
```
to import an entity with default filename, fields and compression instead of:
```
entities:
    household: {}
```
which can be confused with an entity with no initial data and thus no input file, as @benjello did.

**Comment by gdementen** [comment]
why would you want to import an empty entity?

**Comment by benbel** [comment]
To use the entity to store, compute and simulate aggregate values about the simulated population, and hence there is no use for past data for this "aggregate entity".

**Comment by gdementen** [comment]
I would rather have you not import that entity then but still use it in the simulation file. If that does not work (I don't remember), that would be a bug worth fixing.

**Comment by benbel** [comment]
We'll test it with @benjello and let you know.

**Comment by gdementen** [comment]
btw: this behavior (that you get person.csv even if you don't specify it) is even documented, just above the example you quoted:

> if path is omitted, it defaults to a file named after the entity in the same directory than the description file (ie local_path/name_of_the_entity.csv).

In retrospect, I am unsure it was a good idea to implement that behavior, but changing it is just not worth breaking backward compatibility for those relying on it.

**Comment by benbel** [comment]
Indeed it is documented right there, but `{}` strongly suggests an _empty_ set and not a default value, hence the confusion.

**Comment by benjello** [comment]
I reopen this issue. I am trying to use an entity that does not have any data in the initial h5 file.
See [this branch](https://github.com/liam2/liam2/tree/test_empty_entity)

I had to hack `data.py` but still I have index problems.
 ```
 mbenjelloul@pse-ipp-316-0:~/openfisca/liam2$ liam2 run liam2/tests/functional/issue_new.yml 
Warning: the 'view' command is not available because 'vitables' does not seem to be installed correctly (No module named 'qtpy').
Using simulation file: 'liam2/tests/functional/issue_new.yml'
/home/mbenjelloul/openfisca/liam2/liam2/simulation.py:235: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  content = yaml.load(yaml_str)
importing: '/home/mbenjelloul/openfisca/liam2/liam2/tests/examples/demo01.yml'
/home/mbenjelloul/openfisca/liam2/liam2/simulation.py:78: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  import_content = handle_imports(yaml.load(f), import_directory)
reading data from /home/mbenjelloul/openfisca/liam2/liam2/tests/functional/../examples/demo.h5 ...
 * indexing tables
    - generation ... group ``/entities`` does not have a child named ``generation``
    - person ... done (0.01 second elapsed).
'generation'
done (0.01 second elapsed).
 * copying tables
    - generation ... done (1 ms elapsed).
    - person ... done (1 ms elapsed).
done (4 ms elapsed).
 * building arrays for first simulated period
    - generation ... done (0 ms elapsed).
    - person ... done (0 ms elapsed).
done.

=====================
 starting simulation
=====================

period 2015
  * generation: 0 individuals
  * person: 10000 individuals
- 1/2 create_year_of_birth ... 1916 2015 done (0 ms elapsed).
- 2/2 create_year_of_birth ... 2015 1916 1916 1917 1918 1919 1920 1921 1922 1923 1924 1925 1926 1927 1928 1929 1930 1931 1932 1933 1934 1935 1936 1937 1938 1939 1940 1941 1942 1943 1944 1945 1946 1947 1948 1949 1950 1951 1952 1953 1954 1955 1956 1957 1958 1959 1960 1961 1962 1963 1964 1965 1966 1967 1968 1969 1970 1971 1972 1973 1974 1975 1976 1977 1978 1979 1980 1981 1982 1983 1984 1985 1986 1987 1988 1989 1990 1991 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 done (0.03 second elapsed).
- storing period data
  * generation ... done (0 ms elapsed).
    -> 100 individuals
  * person ... done (1 ms elapsed).
    -> 10000 individuals
period 2015 done (0.03 second elapsed).

period 2016
- loading input data
  * generation ... done (0 ms elapsed).
    -> 100 individuals
  * person ... done (0 ms elapsed).
    -> 10000 individuals
- 1/2 ageing ... done (0 ms elapsed).
- 2/2 test_issue ... 
ERROR: index 1959 is out of bounds for axis 0 with size 100
when evaluating: show(generation.year_of_birth)



```

**Comment by gdementen** [comment]
Tentatively adding to 0.13 milestone. It doesn't mean I will fix this but at least understand where the problem comes from
