### ISSUE TITLE
Improve error message to ease solving type error

### ISSUE THREAD

**Issue by benjello** [liam2/liam2#337]
I got this error message and I have no clue how to find the table or variable with the problematic type.
```
Traceback (most recent call last):
  File "/home/benjello/.virtualenvs/aa/bin/liam2", line 11, in <module>
    load_entry_point('liam2', 'console_scripts', 'liam2')()
  File "/home/benjello/openfisca/agirc-arrco-group/agirc-arrco-modeles/build-liam2/liam2/main.py", line 365, in main
    return func(*args)
  File "/home/benjello/openfisca/agirc-arrco-group/agirc-arrco-modeles/build-liam2/liam2/importer.py", line 815, in csv2h5
    buffersize=buffersize, compression=compression)
  File "/home/benjello/openfisca/agirc-arrco-group/agirc-arrco-modeles/build-liam2/liam2/importer.py", line 335, in stream_to_table
    array = fromiter(dataslice, dtype=dtype, count=buffer_rows)
  File "liam2/cutils.pyx", line 16, in cutils.fromiter
    for e in iterable:
  File "/home/benjello/openfisca/agirc-arrco-group/agirc-arrco-modeles/build-liam2/liam2/importer.py", line 71, in convert
    for func, pos in zip(funcs, positions))
  File "/home/benjello/openfisca/agirc-arrco-group/agirc-arrco-modeles/build-liam2/liam2/importer.py", line 71, in <genexpr>
    for func, pos in zip(funcs, positions))
  File "/home/benjello/openfisca/agirc-arrco-group/agirc-arrco-modeles/build-liam2/liam2/importer.py", line 29, in to_int
    return int(v)
ValueError: invalid literal for int() with base 10: '0.0'
```
Any clue on how/where the error message can be improved ?

Thanks !

**Comment by gdementen** [comment]
You should add a string context argument to convert() at
https://github.com/liam2/liam2/blob/669aabe81f757e704f16ea2ddddfe5515c02f972/liam2/importer.py#L51
and fill it with the filename at:
https://github.com/liam2/liam2/blob/669aabe81f757e704f16ea2ddddfe5515c02f972/liam2/importer.py#L263

then at lines https://github.com/liam2/liam2/blob/669aabe81f757e704f16ea2ddddfe5515c02f972/liam2/importer.py#L55
and https://github.com/liam2/liam2/blob/669aabe81f757e704f16ea2ddddfe5515c02f972/liam2/importer.py#L70, you should wrap the yield in a try/except and raise a better exception using the context, the row number and ideally the field name. For the later part, you will have to re-execute the conversion for all fields of the row, with an added try/except for each **value** conversion. I'd rather have that check for each value when we know an exception occurred instead of in the normal code path (done in all cases) to avoid slowing everything down.

**Comment by benjello** [comment]
Hi @gdementen 

I tried to follow your advice and made the following changes

```python
def convert(iterable, fields, positions=None, fpath=None):
    funcs = [converters[type_] for _, type_ in fields]
    if positions is None:
        for row in iterable:
            yield tuple(func(value) for func, value in zip(funcs, row))
    else:
        assert len(positions) <= len(fields)
        rowlen = None
        for row in iterable:
            if rowlen is None:
                rowlen = len(row)
            elif len(row) != rowlen:
                raise Exception("invalid row length (%d != %d): %s"
                                % (len(row), rowlen, row))

            # Note that [x for x in y] is generally faster than
            # tuple(x for x in y) but the stream is usually consumed by
            # fromiter which only accepts tuples (because a[i] = x works only
            # when x is a tuple)
            try:
                yield tuple(func(row[pos])
                            for func, pos in zip(funcs, positions))
            except Exception as e:
                print("when processing row {} file {}".format(row, fpath))
                for func, pos in zip(funcs, positions):
                    try:
                        print(fields[pos])
                        _ = func(row[pos])
                    except Exception as e:
                        print(e)
                        print("field {} is supposed to be of type {}".format(fields[pos][0], fields[pos][1]))
                raise()
'''
I got error messages on type but the field i was catching in the printed error message was not the erroneous one ! (and it got me lost for quite a long time ;-) ) 
Is there something I am missing here ?
Thank you very much !

**Comment by gdementen** [comment]
You should not use fields[pos]. Positions are column indices (relative to the *file* fields, not the *destination* fields stored in the `fields` variable. So you should use something like: for func, pos, (field_name, field_type) in zip(funcs, positions, fields)
